--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaisukeDaisukeTeam/libNpcDialogue
build-by-default: true
branches:
- pm4/main
projects:
  libNpcDialogue:
    path: ""
    model: virion
    type: library
...
